{{- if and (.Values.mongodb.mongoConnectionString.value) ( .Values.mongodb.mongoConnectionString.enableSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sorry-cypress-helm.fullname" . }}-mongodbsecrets
data:
  MONGODB_URI: {{ template "mongodbSecretConnectionString" . }}
{{- end -}}
